# Generated by Django 5.0.4 on 2024-05-18 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('profile_picture', models.ImageField(upload_to='profile_picture/')),
            ],
        ),
        migrations.CreateModel(
            name='Blog_Post_Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('Description', models.TextField()),
                ('tag', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=7)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weblog_apps.categories')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weblog_apps.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField()),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weblog_apps.blog_post_management')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weblog_apps.user')),
            ],
        ),
    ]
