# Generated by Django 5.0.4 on 2024-05-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog_apps', '0002_alter_blog_post_management_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post_management',
            name='image',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
